[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
remappings = [
    '@chainlink/contracts/=node_modules/@chainlink/contracts'
]
[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
milkomedaTestnet = "${MILKOMEDA_TESTNET_RPC_URL}"

[etherscan]
ethereumSepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
